//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JLE.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JLEParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IJLEListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] JLEParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] JLEParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] JLEParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] JLEParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] JLEParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] JLEParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.function_use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_use([NotNull] JLEParser.Function_useContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.function_use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_use([NotNull] JLEParser.Function_useContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] JLEParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] JLEParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.param_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_id_list([NotNull] JLEParser.Param_id_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.param_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_id_list([NotNull] JLEParser.Param_id_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.param_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_decl_list([NotNull] JLEParser.Param_decl_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.param_decl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_decl_list([NotNull] JLEParser.Param_decl_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.param_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_decl([NotNull] JLEParser.Param_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.param_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_decl([NotNull] JLEParser.Param_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JLEParser.param_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_id([NotNull] JLEParser.Param_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JLEParser.param_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_id([NotNull] JLEParser.Param_idContext context);
}
