//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JSON.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class JSONLexer : Lexer {
	public const int
		T__0=1, INT=2, STRING=3, LEFTPAR=4, RIGHTPAR=5, LEFTSQ=6, RIGHTSQ=7, SEMICOLON=8, 
		COMMA=9, WS=10;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "INT", "STRING", "LEFTPAR", "RIGHTPAR", "LEFTSQ", "RIGHTSQ", "SEMICOLON", 
		"COMMA", "WS"
	};


		public Compiler compiler = new Compiler();


	public JSONLexer(ICharStream input)
		: base(input)
	{
		Interpreter = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'for'", null, null, "'('", "')'", "'{'", "'}'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "INT", "STRING", "LEFTPAR", "RIGHTPAR", "LEFTSQ", "RIGHTSQ", 
		"SEMICOLON", "COMMA", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JSON.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x2\f;");
		sb.Append("\b\x1\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6");
		sb.Append("\x4\a\t\a\x4\b\t\b\x4\t\t\t\x4\n\t\n\x4\v\t\v\x3\x2\x3\x2\x3");
		sb.Append("\x2\x3\x2\x3\x3\x5\x3\x1D\n\x3\x3\x3\x6\x3 \n\x3\r\x3\xE\x3");
		sb.Append("!\x3\x4\x6\x4%\n\x4\r\x4\xE\x4&\x3\x5\x3\x5\x3\x6\x3\x6\x3\a");
		sb.Append("\x3\a\x3\b\x3\b\x3\t\x3\t\x3\n\x3\n\x3\v\x6\v\x36\n\v\r\v\xE");
		sb.Append("\v\x37\x3\v\x3\v\x2\x2\f\x3\x3\x5\x4\a\x5\t\x6\v\a\r\b\xF\t");
		sb.Append("\x11\n\x13\v\x15\f\x3\x2\x4\x5\x2\x43\\\x61\x61\x63|\x5\x2\v");
		sb.Append("\f\xF\xF\"\">\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2\x2\x2\x2\a\x3\x2");
		sb.Append("\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2\x2\r\x3\x2\x2\x2\x2");
		sb.Append("\xF\x3\x2\x2\x2\x2\x11\x3\x2\x2\x2\x2\x13\x3\x2\x2\x2\x2\x15");
		sb.Append("\x3\x2\x2\x2\x3\x17\x3\x2\x2\x2\x5\x1C\x3\x2\x2\x2\a$\x3\x2");
		sb.Append("\x2\x2\t(\x3\x2\x2\x2\v*\x3\x2\x2\x2\r,\x3\x2\x2\x2\xF.\x3\x2");
		sb.Append("\x2\x2\x11\x30\x3\x2\x2\x2\x13\x32\x3\x2\x2\x2\x15\x35\x3\x2");
		sb.Append("\x2\x2\x17\x18\ah\x2\x2\x18\x19\aq\x2\x2\x19\x1A\at\x2\x2\x1A");
		sb.Append("\x4\x3\x2\x2\x2\x1B\x1D\a/\x2\x2\x1C\x1B\x3\x2\x2\x2\x1C\x1D");
		sb.Append("\x3\x2\x2\x2\x1D\x1F\x3\x2\x2\x2\x1E \x4\x32;\x2\x1F\x1E\x3");
		sb.Append("\x2\x2\x2 !\x3\x2\x2\x2!\x1F\x3\x2\x2\x2!\"\x3\x2\x2\x2\"\x6");
		sb.Append("\x3\x2\x2\x2#%\t\x2\x2\x2$#\x3\x2\x2\x2%&\x3\x2\x2\x2&$\x3\x2");
		sb.Append("\x2\x2&\'\x3\x2\x2\x2\'\b\x3\x2\x2\x2()\a*\x2\x2)\n\x3\x2\x2");
		sb.Append("\x2*+\a+\x2\x2+\f\x3\x2\x2\x2,-\a}\x2\x2-\xE\x3\x2\x2\x2./\a");
		sb.Append("\x7F\x2\x2/\x10\x3\x2\x2\x2\x30\x31\a=\x2\x2\x31\x12\x3\x2\x2");
		sb.Append("\x2\x32\x33\a.\x2\x2\x33\x14\x3\x2\x2\x2\x34\x36\t\x3\x2\x2");
		sb.Append("\x35\x34\x3\x2\x2\x2\x36\x37\x3\x2\x2\x2\x37\x35\x3\x2\x2\x2");
		sb.Append("\x37\x38\x3\x2\x2\x2\x38\x39\x3\x2\x2\x2\x39:\b\v\x2\x2:\x16");
		sb.Append("\x3\x2\x2\x2\a\x2\x1C!&\x37\x3\b\x2\x2");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
