//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JSON.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class JSONParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, INT=4, STRING=5, LEFTPAR=6, RIGHTPAR=7, LEFTSQ=8, 
		RIGHTSQ=9, SEMICOLON=10, COMMA=11, LESSERTHAN=12, GREATERTHAN=13, PLUS=14, 
		MINUS=15, WS=16;
	public const int
		RULE_start = 0, RULE_prog = 1, RULE_function = 2, RULE_function_use = 3, 
		RULE_function_inside_function = 4, RULE_function_declaration = 5, RULE_for_cycle = 6, 
		RULE_param_id_list = 7, RULE_param_decl_list = 8, RULE_param_decl = 9, 
		RULE_param_id = 10, RULE_statement_list = 11, RULE_statement = 12;
	public static readonly string[] ruleNames = {
		"start", "prog", "function", "function_use", "function_inside_function", 
		"function_declaration", "for_cycle", "param_id_list", "param_decl_list", 
		"param_decl", "param_id", "statement_list", "statement"
	};

	private static readonly string[] _LiteralNames = {
		null, "'for'", "'int'", "'='", null, null, "'('", "')'", "'{'", "'}'", 
		"';'", "','", "'<'", "'>'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "INT", "STRING", "LEFTPAR", "RIGHTPAR", "LEFTSQ", 
		"RIGHTSQ", "SEMICOLON", "COMMA", "LESSERTHAN", "GREATERTHAN", "PLUS", 
		"MINUS", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JSON.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }


		public Compiler compiler = new Compiler();

	public JSONParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class StartContext : ParserRuleContext {
		public ProgContext prog() {
			return GetRuleContext<ProgContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(JSONParser.Eof, 0); }
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26; prog();
			State = 27; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProgContext : ParserRuleContext {
		public FunctionContext[] function() {
			return GetRuleContexts<FunctionContext>();
		}
		public FunctionContext function(int i) {
			return GetRuleContext<FunctionContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 2, RULE_prog);
		try {
			int _alt;
			State = 37;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 30;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 29; function();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 32;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				State = 34; function();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 36; function();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		public Function_useContext function_use() {
			return GetRuleContext<Function_useContext>(0);
		}
		public Function_declarationContext function_declaration() {
			return GetRuleContext<Function_declarationContext>(0);
		}
		public For_cycleContext for_cycle() {
			return GetRuleContext<For_cycleContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 4, RULE_function);
		try {
			State = 42;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39; function_use();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 40; function_declaration();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 41; for_cycle();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_useContext : ParserRuleContext {
		public IToken identifier;
		public Param_id_listContext _param_id_list;
		public IToken _SEMICOLON;
		public ITerminalNode LEFTPAR() { return GetToken(JSONParser.LEFTPAR, 0); }
		public ITerminalNode RIGHTPAR() { return GetToken(JSONParser.RIGHTPAR, 0); }
		public ITerminalNode SEMICOLON() { return GetToken(JSONParser.SEMICOLON, 0); }
		public ITerminalNode STRING() { return GetToken(JSONParser.STRING, 0); }
		public Param_id_listContext param_id_list() {
			return GetRuleContext<Param_id_listContext>(0);
		}
		public Function_useContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_use; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterFunction_use(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitFunction_use(this);
		}
	}

	[RuleVersion(0)]
	public Function_useContext function_use() {
		Function_useContext _localctx = new Function_useContext(Context, State);
		EnterRule(_localctx, 6, RULE_function_use);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44; _localctx.identifier = Match(STRING);
			State = 45; Match(LEFTPAR);
			State = 47;
			_la = TokenStream.La(1);
			if (_la==INT || _la==STRING) {
				{
				State = 46; _localctx._param_id_list = param_id_list();
				}
			}

			State = 49; Match(RIGHTPAR);
			compiler.FunctionManager.addFunctionUse((_localctx.identifier!=null?_localctx.identifier.Text:null), (_localctx._param_id_list!=null?TokenStream.GetText(_localctx._param_id_list.Start,_localctx._param_id_list.Stop):null)); 
			State = 51; _localctx._SEMICOLON = Match(SEMICOLON);
			 compiler.FunctionManager.ErrorManager.checkLineEnding((_localctx._SEMICOLON!=null?_localctx._SEMICOLON.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_inside_functionContext : ParserRuleContext {
		public IToken identifier;
		public Param_id_listContext _param_id_list;
		public IToken _SEMICOLON;
		public ITerminalNode LEFTPAR() { return GetToken(JSONParser.LEFTPAR, 0); }
		public ITerminalNode RIGHTPAR() { return GetToken(JSONParser.RIGHTPAR, 0); }
		public ITerminalNode SEMICOLON() { return GetToken(JSONParser.SEMICOLON, 0); }
		public ITerminalNode STRING() { return GetToken(JSONParser.STRING, 0); }
		public Param_id_listContext param_id_list() {
			return GetRuleContext<Param_id_listContext>(0);
		}
		public Function_inside_functionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_inside_function; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterFunction_inside_function(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitFunction_inside_function(this);
		}
	}

	[RuleVersion(0)]
	public Function_inside_functionContext function_inside_function() {
		Function_inside_functionContext _localctx = new Function_inside_functionContext(Context, State);
		EnterRule(_localctx, 8, RULE_function_inside_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54; _localctx.identifier = Match(STRING);
			State = 55; Match(LEFTPAR);
			State = 57;
			_la = TokenStream.La(1);
			if (_la==INT || _la==STRING) {
				{
				State = 56; _localctx._param_id_list = param_id_list();
				}
			}

			State = 59; Match(RIGHTPAR);
			compiler.FunctionManager.addFunctionToCurrent((_localctx.identifier!=null?_localctx.identifier.Text:null), (_localctx._param_id_list!=null?TokenStream.GetText(_localctx._param_id_list.Start,_localctx._param_id_list.Stop):null)); 
			State = 61; _localctx._SEMICOLON = Match(SEMICOLON);
			 compiler.FunctionManager.ErrorManager.checkLineEnding((_localctx._SEMICOLON!=null?_localctx._SEMICOLON.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_declarationContext : ParserRuleContext {
		public IToken function_type;
		public IToken identifier;
		public ITerminalNode LEFTPAR() { return GetToken(JSONParser.LEFTPAR, 0); }
		public ITerminalNode RIGHTPAR() { return GetToken(JSONParser.RIGHTPAR, 0); }
		public ITerminalNode LEFTSQ() { return GetToken(JSONParser.LEFTSQ, 0); }
		public ITerminalNode RIGHTSQ() { return GetToken(JSONParser.RIGHTSQ, 0); }
		public ITerminalNode[] STRING() { return GetTokens(JSONParser.STRING); }
		public ITerminalNode STRING(int i) {
			return GetToken(JSONParser.STRING, i);
		}
		public Param_decl_listContext param_decl_list() {
			return GetRuleContext<Param_decl_listContext>(0);
		}
		public Function_inside_functionContext[] function_inside_function() {
			return GetRuleContexts<Function_inside_functionContext>();
		}
		public Function_inside_functionContext function_inside_function(int i) {
			return GetRuleContext<Function_inside_functionContext>(i);
		}
		public For_cycleContext[] for_cycle() {
			return GetRuleContexts<For_cycleContext>();
		}
		public For_cycleContext for_cycle(int i) {
			return GetRuleContext<For_cycleContext>(i);
		}
		public Function_declarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterFunction_declaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitFunction_declaration(this);
		}
	}

	[RuleVersion(0)]
	public Function_declarationContext function_declaration() {
		Function_declarationContext _localctx = new Function_declarationContext(Context, State);
		EnterRule(_localctx, 10, RULE_function_declaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64; _localctx.function_type = Match(STRING);
			State = 65; _localctx.identifier = Match(STRING);
			compiler.FunctionManager.addDeclaredFunction((_localctx.function_type!=null?_localctx.function_type.Text:null), (_localctx.identifier!=null?_localctx.identifier.Text:null)); 
			State = 67; Match(LEFTPAR);
			State = 69;
			_la = TokenStream.La(1);
			if (_la==STRING) {
				{
				State = 68; param_decl_list();
				}
			}

			State = 71; Match(RIGHTPAR);
			State = 72; Match(LEFTSQ);
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==T__0 || _la==STRING) {
				{
				State = 75;
				switch (TokenStream.La(1)) {
				case STRING:
					{
					State = 73; function_inside_function();
					}
					break;
				case T__0:
					{
					State = 74; for_cycle();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 80; Match(RIGHTSQ);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_cycleContext : ParserRuleContext {
		public IToken val_dec;
		public IToken val_init;
		public IToken val_use;
		public IToken val_total;
		public IToken val_inc;
		public ITerminalNode LEFTPAR() { return GetToken(JSONParser.LEFTPAR, 0); }
		public ITerminalNode[] SEMICOLON() { return GetTokens(JSONParser.SEMICOLON); }
		public ITerminalNode SEMICOLON(int i) {
			return GetToken(JSONParser.SEMICOLON, i);
		}
		public ITerminalNode LESSERTHAN() { return GetToken(JSONParser.LESSERTHAN, 0); }
		public ITerminalNode[] PLUS() { return GetTokens(JSONParser.PLUS); }
		public ITerminalNode PLUS(int i) {
			return GetToken(JSONParser.PLUS, i);
		}
		public ITerminalNode RIGHTPAR() { return GetToken(JSONParser.RIGHTPAR, 0); }
		public ITerminalNode LEFTSQ() { return GetToken(JSONParser.LEFTSQ, 0); }
		public ITerminalNode RIGHTSQ() { return GetToken(JSONParser.RIGHTSQ, 0); }
		public ITerminalNode[] STRING() { return GetTokens(JSONParser.STRING); }
		public ITerminalNode STRING(int i) {
			return GetToken(JSONParser.STRING, i);
		}
		public ITerminalNode[] INT() { return GetTokens(JSONParser.INT); }
		public ITerminalNode INT(int i) {
			return GetToken(JSONParser.INT, i);
		}
		public Function_inside_functionContext[] function_inside_function() {
			return GetRuleContexts<Function_inside_functionContext>();
		}
		public Function_inside_functionContext function_inside_function(int i) {
			return GetRuleContext<Function_inside_functionContext>(i);
		}
		public For_cycleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_cycle; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterFor_cycle(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitFor_cycle(this);
		}
	}

	[RuleVersion(0)]
	public For_cycleContext for_cycle() {
		For_cycleContext _localctx = new For_cycleContext(Context, State);
		EnterRule(_localctx, 12, RULE_for_cycle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82; Match(T__0);
			State = 83; Match(LEFTPAR);
			State = 84; Match(T__1);
			State = 85; _localctx.val_dec = Match(STRING);
			State = 86; Match(T__2);
			State = 87; _localctx.val_init = Match(INT);
			State = 88; Match(SEMICOLON);
			State = 89; _localctx.val_use = Match(STRING);
			State = 90; Match(LESSERTHAN);
			State = 91; _localctx.val_total = Match(INT);
			State = 92; Match(SEMICOLON);
			State = 93; _localctx.val_inc = Match(STRING);
			State = 94; Match(PLUS);
			State = 95; Match(PLUS);
			State = 96; Match(RIGHTPAR);
			 compiler.FunctionManager.addForCycle((_localctx.val_dec!=null?_localctx.val_dec.Text:null), (_localctx.val_init!=null?_localctx.val_init.Text:null), (_localctx.val_use!=null?_localctx.val_use.Text:null), (_localctx.val_total!=null?_localctx.val_total.Text:null), (_localctx.val_inc!=null?_localctx.val_inc.Text:null)); 
			State = 98; Match(LEFTSQ);
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==STRING) {
				{
				{
				State = 99; function_inside_function();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			State = 105; Match(RIGHTSQ);
			 compiler.FunctionManager.addForCycleCommands(); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_id_listContext : ParserRuleContext {
		public Param_idContext[] param_id() {
			return GetRuleContexts<Param_idContext>();
		}
		public Param_idContext param_id(int i) {
			return GetRuleContext<Param_idContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(JSONParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JSONParser.COMMA, i);
		}
		public Param_id_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_id_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterParam_id_list(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitParam_id_list(this);
		}
	}

	[RuleVersion(0)]
	public Param_id_listContext param_id_list() {
		Param_id_listContext _localctx = new Param_id_listContext(Context, State);
		EnterRule(_localctx, 14, RULE_param_id_list);
		try {
			int _alt;
			State = 118;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 111;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 108; param_id();
						State = 109; Match(COMMA);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 113;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				State = 115; param_id();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 117; param_id();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_decl_listContext : ParserRuleContext {
		public Param_declContext[] param_decl() {
			return GetRuleContexts<Param_declContext>();
		}
		public Param_declContext param_decl(int i) {
			return GetRuleContext<Param_declContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(JSONParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JSONParser.COMMA, i);
		}
		public Param_decl_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_decl_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterParam_decl_list(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitParam_decl_list(this);
		}
	}

	[RuleVersion(0)]
	public Param_decl_listContext param_decl_list() {
		Param_decl_listContext _localctx = new Param_decl_listContext(Context, State);
		EnterRule(_localctx, 16, RULE_param_decl_list);
		try {
			int _alt;
			State = 130;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 123;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 120; param_decl();
						State = 121; Match(COMMA);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 125;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
				State = 127; param_decl();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 129; param_decl();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_declContext : ParserRuleContext {
		public IToken param_type;
		public IToken param_identifier;
		public ITerminalNode[] STRING() { return GetTokens(JSONParser.STRING); }
		public ITerminalNode STRING(int i) {
			return GetToken(JSONParser.STRING, i);
		}
		public Param_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_decl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterParam_decl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitParam_decl(this);
		}
	}

	[RuleVersion(0)]
	public Param_declContext param_decl() {
		Param_declContext _localctx = new Param_declContext(Context, State);
		EnterRule(_localctx, 18, RULE_param_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132; _localctx.param_type = Match(STRING);
			State = 133; _localctx.param_identifier = Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Param_idContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(JSONParser.STRING, 0); }
		public ITerminalNode INT() { return GetToken(JSONParser.INT, 0); }
		public Param_idContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_param_id; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterParam_id(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitParam_id(this);
		}
	}

	[RuleVersion(0)]
	public Param_idContext param_id() {
		Param_idContext _localctx = new Param_idContext(Context, State);
		EnterRule(_localctx, 20, RULE_param_id);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			_la = TokenStream.La(1);
			if ( !(_la==INT || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_listContext : ParserRuleContext {
		public Statement_listContext statement_list() {
			return GetRuleContext<Statement_listContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public Statement_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterStatement_list(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitStatement_list(this);
		}
	}

	[RuleVersion(0)]
	public Statement_listContext statement_list() {
		return statement_list(0);
	}

	private Statement_listContext statement_list(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Statement_listContext _localctx = new Statement_listContext(Context, _parentState);
		Statement_listContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_statement_list, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 142;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Statement_listContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_statement_list);
					State = 138;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 139; statement();
					}
					} 
				}
				State = 144;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public Function_useContext function_use() {
			return GetRuleContext<Function_useContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IJSONListener typedListener = listener as IJSONListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145; function_use();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 11: return statement_list_sempred((Statement_listContext)_localctx, predIndex);
		}
		return true;
	}
	private bool statement_list_sempred(Statement_listContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}

	private static string _serializedATN = _serializeATN();
	private static string _serializeATN()
	{
	    StringBuilder sb = new StringBuilder();
	    sb.Append("\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x12");
		sb.Append("\x96\x4\x2\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6");
		sb.Append("\x4\a\t\a\x4\b\t\b\x4\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r");
		sb.Append("\t\r\x4\xE\t\xE\x3\x2\x3\x2\x3\x2\x3\x3\x6\x3!\n\x3\r\x3\xE");
		sb.Append("\x3\"\x3\x3\x3\x3\x3\x3\x5\x3(\n\x3\x3\x4\x3\x4\x3\x4\x5\x4");
		sb.Append("-\n\x4\x3\x5\x3\x5\x3\x5\x5\x5\x32\n\x5\x3\x5\x3\x5\x3\x5\x3");
		sb.Append("\x5\x3\x5\x3\x6\x3\x6\x3\x6\x5\x6<\n\x6\x3\x6\x3\x6\x3\x6\x3");
		sb.Append("\x6\x3\x6\x3\a\x3\a\x3\a\x3\a\x3\a\x5\aH\n\a\x3\a\x3\a\x3\a");
		sb.Append("\x3\a\a\aN\n\a\f\a\xE\aQ\v\a\x3\a\x3\a\x3\b\x3\b\x3\b\x3\b\x3");
		sb.Append("\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3\b\x3");
		sb.Append("\b\x3\b\a\bg\n\b\f\b\xE\bj\v\b\x3\b\x3\b\x3\b\x3\t\x3\t\x3\t");
		sb.Append("\x6\tr\n\t\r\t\xE\ts\x3\t\x3\t\x3\t\x5\ty\n\t\x3\n\x3\n\x3\n");
		sb.Append("\x6\n~\n\n\r\n\xE\n\x7F\x3\n\x3\n\x3\n\x5\n\x85\n\n\x3\v\x3");
		sb.Append("\v\x3\v\x3\f\x3\f\x3\r\x3\r\x3\r\a\r\x8F\n\r\f\r\xE\r\x92\v");
		sb.Append("\r\x3\xE\x3\xE\x3\xE\x2\x3\x18\xF\x2\x4\x6\b\n\f\xE\x10\x12");
		sb.Append("\x14\x16\x18\x1A\x2\x3\x3\x2\x6\a\x97\x2\x1C\x3\x2\x2\x2\x4");
		sb.Append("\'\x3\x2\x2\x2\x6,\x3\x2\x2\x2\b.\x3\x2\x2\x2\n\x38\x3\x2\x2");
		sb.Append("\x2\f\x42\x3\x2\x2\x2\xET\x3\x2\x2\x2\x10x\x3\x2\x2\x2\x12\x84");
		sb.Append("\x3\x2\x2\x2\x14\x86\x3\x2\x2\x2\x16\x89\x3\x2\x2\x2\x18\x8B");
		sb.Append("\x3\x2\x2\x2\x1A\x93\x3\x2\x2\x2\x1C\x1D\x5\x4\x3\x2\x1D\x1E");
		sb.Append("\a\x2\x2\x3\x1E\x3\x3\x2\x2\x2\x1F!\x5\x6\x4\x2 \x1F\x3\x2\x2");
		sb.Append("\x2!\"\x3\x2\x2\x2\" \x3\x2\x2\x2\"#\x3\x2\x2\x2#$\x3\x2\x2");
		sb.Append("\x2$%\x5\x6\x4\x2%(\x3\x2\x2\x2&(\x5\x6\x4\x2\' \x3\x2\x2\x2");
		sb.Append("\'&\x3\x2\x2\x2(\x5\x3\x2\x2\x2)-\x5\b\x5\x2*-\x5\f\a\x2+-\x5");
		sb.Append("\xE\b\x2,)\x3\x2\x2\x2,*\x3\x2\x2\x2,+\x3\x2\x2\x2-\a\x3\x2");
		sb.Append("\x2\x2./\a\a\x2\x2/\x31\a\b\x2\x2\x30\x32\x5\x10\t\x2\x31\x30");
		sb.Append("\x3\x2\x2\x2\x31\x32\x3\x2\x2\x2\x32\x33\x3\x2\x2\x2\x33\x34");
		sb.Append("\a\t\x2\x2\x34\x35\b\x5\x1\x2\x35\x36\a\f\x2\x2\x36\x37\b\x5");
		sb.Append("\x1\x2\x37\t\x3\x2\x2\x2\x38\x39\a\a\x2\x2\x39;\a\b\x2\x2:<");
		sb.Append("\x5\x10\t\x2;:\x3\x2\x2\x2;<\x3\x2\x2\x2<=\x3\x2\x2\x2=>\a\t");
		sb.Append("\x2\x2>?\b\x6\x1\x2?@\a\f\x2\x2@\x41\b\x6\x1\x2\x41\v\x3\x2");
		sb.Append("\x2\x2\x42\x43\a\a\x2\x2\x43\x44\a\a\x2\x2\x44\x45\b\a\x1\x2");
		sb.Append("\x45G\a\b\x2\x2\x46H\x5\x12\n\x2G\x46\x3\x2\x2\x2GH\x3\x2\x2");
		sb.Append("\x2HI\x3\x2\x2\x2IJ\a\t\x2\x2JO\a\n\x2\x2KN\x5\n\x6\x2LN\x5");
		sb.Append("\xE\b\x2MK\x3\x2\x2\x2ML\x3\x2\x2\x2NQ\x3\x2\x2\x2OM\x3\x2\x2");
		sb.Append("\x2OP\x3\x2\x2\x2PR\x3\x2\x2\x2QO\x3\x2\x2\x2RS\a\v\x2\x2S\r");
		sb.Append("\x3\x2\x2\x2TU\a\x3\x2\x2UV\a\b\x2\x2VW\a\x4\x2\x2WX\a\a\x2");
		sb.Append("\x2XY\a\x5\x2\x2YZ\a\x6\x2\x2Z[\a\f\x2\x2[\\\a\a\x2\x2\\]\a");
		sb.Append("\xE\x2\x2]^\a\x6\x2\x2^_\a\f\x2\x2_`\a\a\x2\x2`\x61\a\x10\x2");
		sb.Append("\x2\x61\x62\a\x10\x2\x2\x62\x63\a\t\x2\x2\x63\x64\b\b\x1\x2");
		sb.Append("\x64h\a\n\x2\x2\x65g\x5\n\x6\x2\x66\x65\x3\x2\x2\x2gj\x3\x2");
		sb.Append("\x2\x2h\x66\x3\x2\x2\x2hi\x3\x2\x2\x2ik\x3\x2\x2\x2jh\x3\x2");
		sb.Append("\x2\x2kl\a\v\x2\x2lm\b\b\x1\x2m\xF\x3\x2\x2\x2no\x5\x16\f\x2");
		sb.Append("op\a\r\x2\x2pr\x3\x2\x2\x2qn\x3\x2\x2\x2rs\x3\x2\x2\x2sq\x3");
		sb.Append("\x2\x2\x2st\x3\x2\x2\x2tu\x3\x2\x2\x2uv\x5\x16\f\x2vy\x3\x2");
		sb.Append("\x2\x2wy\x5\x16\f\x2xq\x3\x2\x2\x2xw\x3\x2\x2\x2y\x11\x3\x2");
		sb.Append("\x2\x2z{\x5\x14\v\x2{|\a\r\x2\x2|~\x3\x2\x2\x2}z\x3\x2\x2\x2");
		sb.Append("~\x7F\x3\x2\x2\x2\x7F}\x3\x2\x2\x2\x7F\x80\x3\x2\x2\x2\x80\x81");
		sb.Append("\x3\x2\x2\x2\x81\x82\x5\x14\v\x2\x82\x85\x3\x2\x2\x2\x83\x85");
		sb.Append("\x5\x14\v\x2\x84}\x3\x2\x2\x2\x84\x83\x3\x2\x2\x2\x85\x13\x3");
		sb.Append("\x2\x2\x2\x86\x87\a\a\x2\x2\x87\x88\a\a\x2\x2\x88\x15\x3\x2");
		sb.Append("\x2\x2\x89\x8A\t\x2\x2\x2\x8A\x17\x3\x2\x2\x2\x8B\x90\b\r\x1");
		sb.Append("\x2\x8C\x8D\f\x4\x2\x2\x8D\x8F\x5\x1A\xE\x2\x8E\x8C\x3\x2\x2");
		sb.Append("\x2\x8F\x92\x3\x2\x2\x2\x90\x8E\x3\x2\x2\x2\x90\x91\x3\x2\x2");
		sb.Append("\x2\x91\x19\x3\x2\x2\x2\x92\x90\x3\x2\x2\x2\x93\x94\x5\b\x5");
		sb.Append("\x2\x94\x1B\x3\x2\x2\x2\x10\"\',\x31;GMOhsx\x7F\x84\x90");
	    return sb.ToString();
	}

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
